name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
